language: node_js

node_js:
  - "1.0.0"

sudo: required

services:
  - docker

before_script:
  -  npm install
  -  npm pack

script:
  - docker build -t hello .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag hello $DOCKER_USER/hello:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/hello:$TRAVIS_BUILD_NUMBER 
